# Generated by Django 3.2.6 on 2021-10-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oa',
            name='conteudo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oa',
            name='descricao',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='oa',
            name='link',
            field=models.CharField(max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='oa',
            name='tag',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
