# Generated by Django 3.2.6 on 2021-10-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211015_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nometag', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='oa',
            name='tag',
        ),
    ]
