# Generated by Django 3.2.6 on 2021-10-15 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211015_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='oa',
            name='tag',
            field=models.ManyToManyField(to='app.Tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='nometag',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
