# Generated by Django 3.2.6 on 2021-10-15 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211015_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oa',
            name='inserir',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
