# Generated by Django 3.2.6 on 2021-10-15 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20211015_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ano_Escolar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_escolar', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_disciplina', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='oa',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='oa',
            name='conteudo',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
