# Generated by Django 3.2.6 on 2021-10-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20211015_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ano_Escolar',
        ),
        migrations.AddField(
            model_name='conteudo',
            name='ano',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='conteudo',
            name='disciplina',
            field=models.ManyToManyField(to='app.Disciplina'),
        ),
        migrations.RemoveField(
            model_name='oa',
            name='conteudo',
        ),
        migrations.AddField(
            model_name='oa',
            name='conteudo',
            field=models.ManyToManyField(to='app.Conteudo'),
        ),
    ]
