# Generated by Django 3.2.6 on 2021-10-15 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211015_1232'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
