# Generated by Django 3.2.6 on 2021-10-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20211027_1531'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
