# Generated by Django 3.2.6 on 2021-10-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_delete_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oa',
            name='inserir',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
