# Generated by Django 3.2.6 on 2021-12-03 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_oa_inserir'),
    ]

    operations = [
        migrations.AddField(
            model_name='oa',
            name='autor',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
