# Generated by Django 3.2.6 on 2021-12-20 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20211220_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oa',
            name='imagem',
            field=models.ImageField(blank=True, default='logo.png', null=True, upload_to='app/static/images/'),
        ),
    ]
