# Generated by Django 3.2.6 on 2021-12-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_oa_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oa',
            name='imagem',
            field=models.ImageField(default='app/static/images/logo.png', upload_to='app/static/images/'),
        ),
    ]
