# Generated by Django 3.2.6 on 2021-12-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_oa_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oa',
            name='autor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='oa',
            name='descricao',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
    ]
