# Generated by Django 3.2.6 on 2021-12-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20211220_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oa',
            name='imagem',
            field=models.ImageField(default='imagens/uploads/logo.png', upload_to='imagens/uploads/'),
        ),
    ]
